#!/bin/bash

ENVIRONMENT={{{ENVIRONMENT}}}
APPLICATION={{{APPLICATION}}}
REGION={{{REGION}}}
LOGSTREAM=nbt-{{{ENVIRONMENT}}}-{{{APPLICATION}}}-logs
#S3_BUCKET=s3://nbt-{{{ENVIRONMENT}}}-configs

# Our application
V_APPLICATION_PORT=8080

# Database
V_DB_HOST=nbt-{{{ENVIRONMENT}}}.cluster-xxxxxxxxxxxx.ap-northeast-1.rds.amazonaws.com
V_DB_PORT=3306
V_DB_NAME=xxxxx
V_DB_USERNAME=xxxxx
V_DB_PASSWORD=xxxxxxxx

# Cache
V_REDIS_HOST=nbt-{{{ENVIRONMENT}}}-cache.xxxxxx.xxxx.xxxxx.cache.amazonaws.com
V_REDIS_PORT=6379

# Custom variables - prefix with "V_"
V_SOMETHING=whatever
