
// AWS Node types
module.exports.SUBNET = 'Subnet'
module.exports.SECGRP = 'Security Group'
module.exports.VPC = 'Virtual Private Cloud'
module.exports.NAT = 'NAT Gateway'
module.exports.IGW = 'Internet Gateway'
module.exports.INSTANCE = 'EC2 Instance'
module.exports.JUMPBOX = 'Jumpbox' // EC2 Instance, with Tag Name = '*-jumpbox-*'
module.exports.IMAGE = 'AMI Image'
module.exports.AZ = 'Availability Zone'
module.exports.ADDR = 'Elastic IP'
module.exports.COSTCD = 'Cost Code'
module.exports.LOGICAL = 'Logical Grouping'
module.exports.PUBLICIP = 'Public IP Address'
module.exports.KEYPAIR = 'Key Pair'
module.exports.NETIFACE = 'Network Interface'
module.exports.ROUTETABLE = 'Route Table'
module.exports.ALB = 'Load Balancer'
module.exports.TARGETGRP = 'Target Group'
module.exports.LISTENER = 'Listener'
module.exports.RULE = 'Rule'
module.exports.CLUSTER = 'Cluster'
module.exports.SERVICE = 'Service'
module.exports.TASK = 'Task'
