#!/bin/bash
#
#	Run the healthcheck via the ALB
#
. $(dirname $0)/SETENV

echo "$" curl -v http://127.0.0.1:${AUTHSERVICE_PORT_EXTERNAL}/v1/healthcheck
         curl -v http://127.0.0.1:${AUTHSERVICE_PORT_EXTERNAL}/v1/healthcheck
