#!/bin/bash
. $(dirname $0)/SETENV


# Create the databases
CMD="docker run -i --rm mysql mysql -h ${DB_HOST} -u ${DB_USERNAME} -p${DB_PASSWORD}"
echo CMD=${CMD}

${CMD} << END3
DROP DATABASE ${DB_NAME} ;
END3

${CMD} << END4
CREATE DATABASE ${DB_NAME} ;

GRANT ALL PRIVILEGES ON ${DB_NAME} . * TO '${DB_USERNAME}'@'%' WITH GRANT OPTION ;

show databases;
END4

exit 0
